In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = sns.load_dataset('titanic')

In [3]:
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [4]:
df.dropna(inplace=True)

In [5]:
df['survived'].unique()

array([1, 0], dtype=int64)

In [6]:
y = df['survived']
y.shape

(182,)

In [7]:
df['age'].unique()

array([38.  , 35.  , 54.  ,  4.  , 58.  , 34.  , 28.  , 19.  , 49.  ,
       65.  , 45.  , 29.  , 25.  , 23.  , 46.  , 71.  , 21.  , 47.  ,
       24.  , 32.5 , 37.  , 36.5 , 22.  , 61.  , 56.  , 50.  ,  1.  ,
        3.  , 44.  ,  2.  , 40.  , 31.  , 32.  , 62.  , 30.  , 52.  ,
       63.  , 36.  ,  0.92, 17.  , 18.  , 16.  , 45.5 , 41.  , 60.  ,
       27.  , 33.  , 14.  , 64.  , 48.  , 55.  , 39.  , 53.  , 42.  ,
       80.  , 15.  , 70.  ,  6.  , 51.  , 57.  , 43.  , 11.  , 26.  ])

In [8]:
X = df[['pclass', 'sex', 'age']]
X.head()

pclass     sex   age
1        1  female  38.0
3        1  female  35.0
6        1    male  54.0
10       3  female   4.0
11       1  female  58.0

In [9]:
from sklearn.preprocessing import LabelBinarizer

In [10]:
lb = LabelBinarizer()
X[['sex']] = lb.fit_transform(df[['sex']])
X.head()

C:\Users\office\Anaconda3\envs\Tree\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
C:\Users\office\Anaconda3\envs\Tree\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s


pclass  sex   age
1        1    0  38.0
3        1    0  35.0
6        1    1  54.0
10       3    0   4.0
11       1    0  58.0

In [11]:
X['sex'].value_counts()

1    94
0    88
Name: sex, dtype: int64

In [12]:
df['sex'].value_counts()

male      94
female    88
Name: sex, dtype: int64

In [13]:
X.describe()

pclass         sex         age
count  182.000000  182.000000  182.000000
mean     1.192308    0.516484   35.623187
std      0.516411    0.501107   15.671615
min      1.000000    0.000000    0.920000
25%      1.000000    0.000000   24.000000
50%      1.000000    1.000000   36.000000
75%      1.000000    1.000000   47.750000
max      3.000000    1.000000   80.000000

In [14]:
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.tree import DecisionTreeClassifier

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

In [16]:
def print_score(clf, X_train, X_test, y_train, y_test, train = True):
    '''
    To Print the accuracy score, Precision and recall score with confusion metrcis
    '''
    if train:
        '''
        Print the score of train datasets
        '''
        print("Accuracy score: \t{0:.4f}".format(accuracy_score(y_train, clf.predict(X_train))))
        print("classification_report: \n {} \n".format(classification_report(y_train, clf.predict(X_train))))
        print("confusion matrics: \n {} \n".format(confusion_matrix(y_train, clf.predict(X_train))))
        
        res = cross_val_score(clf, X_train, y_train, cv = 10, scoring = 'accuracy')
        print("Accuracy: \t {0:.4f} \nSD: \t\t{1:.4f}".format(np.mean(res), np.std(res)))
        
    elif train == False:
        '''
        Print the score of test sets
        '''
        print("Accuracy score: \t {0:.4f}".format(accuracy_score(y_test,clf.predict(X_test))))
        print("classification_report: \n {} \n".format(classification_report(y_test, clf.predict(X_test))))
        print("confusion matrics: \n {} \n".format(confusion_matrix(y_test, clf.predict(X_test))))
        
        

In [17]:
clf = DecisionTreeClassifier(random_state=42)
clf.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=42,
            splitter='best')

In [18]:
print_score(clf, X_train, X_test, y_train, y_test, train = True)

Accuracy score: 	0.9606
classification_report: 
               precision    recall  f1-score   support

           0       0.90      0.97      0.94        37
           1       0.99      0.96      0.97        90

   micro avg       0.96      0.96      0.96       127
   macro avg       0.94      0.96      0.95       127
weighted avg       0.96      0.96      0.96       127
 

confusion matrics: 
 [[36  1]
 [ 4 86]] 

Accuracy: 	 0.7641 
SD: 		0.1119


In [19]:
print_score(clf, X_train, X_test, y_train, y_test, train = False)

Accuracy score: 	 0.7091
classification_report: 
               precision    recall  f1-score   support

           0       0.65      0.59      0.62        22
           1       0.74      0.79      0.76        33

   micro avg       0.71      0.71      0.71        55
   macro avg       0.70      0.69      0.69        55
weighted avg       0.71      0.71      0.71        55
 

confusion matrics: 
 [[13  9]
 [ 7 26]] 



# Bagging ( oob_score = False)
## oob_score specifies sampling is to be done or not

In [29]:
from sklearn.ensemble import BaggingClassifier

In [39]:
bgng_clf = BaggingClassifier(base_estimator = clf,
                             n_estimators = 5000,
                             bootstrap=True,                             
                             n_jobs = -1,
                             random_state = 42)

In [40]:
bgng_clf.fit(X_train, y_train)

BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=42,
            splitter='best'),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=1.0, n_estimators=5000, n_jobs=-1, oob_score=False,
         random_state=42, verbose=0, warm_start=False)

In [41]:
print_score(bgng_clf, X_train, X_test, y_train, y_test, train = True)

Accuracy score: 	0.9606
classification_report: 
               precision    recall  f1-score   support

           0       0.94      0.92      0.93        37
           1       0.97      0.98      0.97        90

   micro avg       0.96      0.96      0.96       127
   macro avg       0.96      0.95      0.95       127
weighted avg       0.96      0.96      0.96       127
 

confusion matrics: 
 [[34  3]
 [ 2 88]] 

Accuracy: 	 0.7487 
SD: 		0.1299


In [42]:
print_score(bgng_clf, X_train, X_test, y_train, y_test, train = False)

Accuracy score: 	 0.7455
classification_report: 
               precision    recall  f1-score   support

           0       0.72      0.59      0.65        22
           1       0.76      0.85      0.80        33

   micro avg       0.75      0.75      0.75        55
   macro avg       0.74      0.72      0.73        55
weighted avg       0.74      0.75      0.74        55
 

confusion matrics: 
 [[13  9]
 [ 5 28]] 



# Bagging( oob_score = True)

In [43]:
bgng_clf = BaggingClassifier(base_estimator = clf,
                             n_estimators = 5000,
                             bootstrap=True,
                             oob_score = True,
                             n_jobs = -1,
                             random_state = 42)

In [44]:
bgng_clf.fit(X_train, y_train)

BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=42,
            splitter='best'),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=1.0, n_estimators=5000, n_jobs=-1, oob_score=True,
         random_state=42, verbose=0, warm_start=False)

In [45]:
print_score(bgng_clf, X_train, X_test, y_train, y_test, train = True)

Accuracy score: 	0.9606
classification_report: 
               precision    recall  f1-score   support

           0       0.94      0.92      0.93        37
           1       0.97      0.98      0.97        90

   micro avg       0.96      0.96      0.96       127
   macro avg       0.96      0.95      0.95       127
weighted avg       0.96      0.96      0.96       127
 

confusion matrics: 
 [[34  3]
 [ 2 88]] 

Accuracy: 	 0.7487 
SD: 		0.1299


In [46]:
print_score(bgng_clf, X_train, X_test, y_train, y_test, train = False)

Accuracy score: 	 0.7455
classification_report: 
               precision    recall  f1-score   support

           0       0.72      0.59      0.65        22
           1       0.76      0.85      0.80        33

   micro avg       0.75      0.75      0.75        55
   macro avg       0.74      0.72      0.73        55
weighted avg       0.74      0.75      0.74        55
 

confusion matrics: 
 [[13  9]
 [ 5 28]] 

